"use client";

import { useEffect, useId, useRef } from "react";
import { createPortal } from "react-dom";
import { MapPin, PackageCheck, RefreshCw, Truck, X } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { formatMinor } from "@/lib/commerce/client";
import type { CheckoutCopy } from "@/lib/i18n/checkout-copy";
import type { Locale } from "@/lib/i18n/config";

type LocalizedText = { fa?: string; en?: string; ar?: string };
export type FulfillmentPlan = { fulfillable: boolean; fulfillmentPlanHash: string | null; currency: string; subtotalMinor: number; shippingMinor: number; totalMinor: number; shipmentCount: number; unavailableItems?: Array<{ variantId: string; requested: number; available: number; productName: LocalizedText; colorName: LocalizedText; sizeName: LocalizedText; sku: string }>; shipments: Array<{ storeId: string; cityId: string; storeCode: string; storeName: LocalizedText; address?: LocalizedText | null; shippingMinor: number; items: Array<{ variantId: string; locationId: string; quantity: number; productName: LocalizedText; colorName: LocalizedText; sizeName: LocalizedText; sku: string }> }> };
type Props = { open: boolean; locale: Locale; copy: CheckoutCopy; plan?: FulfillmentPlan; loading: boolean; error: boolean; confirming: boolean; onClose: () => void; onConfirm: () => void; onRetry: () => void };

export function StoreSelectionModal({ open, locale, copy, plan, loading, error, confirming, onClose, onConfirm, onRetry }: Props) {
  const titleId = useId(); const descriptionId = useId(); const dialogRef = useRef<HTMLDivElement>(null);
  useEffect(() => { if (!open) return; const overflow = document.body.style.overflow; document.body.style.overflow = "hidden"; const dialog = dialogRef.current; dialog?.querySelector<HTMLElement>('button:not([disabled]), [href], [tabindex]:not([tabindex="-1"])')?.focus(); const key = (event: KeyboardEvent) => { if (event.key === "Escape") { event.preventDefault(); onClose(); return; } if (event.key !== "Tab" || !dialog) return; const nodes = [...dialog.querySelectorAll<HTMLElement>('button:not([disabled]), [href], [tabindex]:not([tabindex="-1"])')]; if (!nodes.length) return; if (event.shiftKey && document.activeElement === nodes[0]) { event.preventDefault(); nodes.at(-1)?.focus(); } else if (!event.shiftKey && document.activeElement === nodes.at(-1)) { event.preventDefault(); nodes[0].focus(); } }; document.addEventListener("keydown", key); return () => { document.body.style.overflow = overflow; document.removeEventListener("keydown", key); }; }, [onClose, open]);
  if (!open || typeof document === "undefined") return null;
  return createPortal(<div className="fixed inset-0 z-[100] grid items-end bg-black/60 sm:place-items-center sm:p-6" onMouseDown={(event) => { if (event.target === event.currentTarget && !confirming) onClose(); }}><div ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby={titleId} aria-describedby={descriptionId} dir={locale === "en" ? "ltr" : "rtl"} lang={locale} className="max-h-[94dvh] w-full overflow-y-auto bg-[#F6F2EB] text-[#0B0B0B] shadow-2xl sm:max-w-3xl sm:border-t-2 sm:border-[#C15427]">
    <header className="sticky top-0 z-10 flex items-start justify-between gap-6 border-b border-black/15 bg-[#F6F2EB]/95 px-5 py-5 backdrop-blur sm:px-8 sm:py-7"><div><p className="text-[10px] font-semibold tracking-[.14em] text-[#C15427]">{copy.deliveryPlan}</p><h2 id={titleId} className="mt-2 text-2xl font-semibold sm:text-3xl">{copy.modalTitle}</h2><p id={descriptionId} className="mt-3 max-w-2xl text-xs leading-6 text-black/65">{copy.modalDescription}</p></div><button type="button" disabled={confirming} onClick={onClose} aria-label={copy.close} className="grid size-11 shrink-0 place-items-center border border-black/20 bg-white focus-visible:outline-2 focus-visible:outline-[#C15427] disabled:opacity-40"><X className="size-4" /></button></header>
    <div className="px-5 py-6 sm:px-8 sm:py-8">{loading ? <div className="space-y-3" role="status"><p className="text-xs text-black/60">{copy.loading}</p>{[0,1].map((i) => <div key={i} className="h-36 animate-pulse border border-black/10 bg-white" />)}</div> : error ? <State text={copy.loadError}><Button type="button" variant="black" onClick={onRetry}><RefreshCw className="size-4" />{copy.retry}</Button></State> : !plan?.fulfillable || !plan.shipments.length ? <State text={copy.noStoreAnywhere}><ul className="mb-6 mt-4 space-y-2 text-start">{plan?.unavailableItems?.map((item) => <li key={item.variantId} className="border border-black/10 p-3 text-xs"><strong>{localize(item.productName, locale, item.sku)}</strong><span className="mt-1 block text-black/60">{localize(item.colorName, locale)} · {localize(item.sizeName, locale)} — {copy.requested}: {item.requested} / {copy.available}: {item.available}</span></li>)}</ul><Button type="button" variant="outline" onClick={onRetry}>{copy.retry}</Button></State> : <>
      <div className="mb-5 flex items-center justify-between border-y border-black/15 py-4"><span className="inline-flex items-center gap-2 text-xs font-semibold"><Truck className="size-4 text-[#C15427]" />{plan.shipmentCount} {copy.shipments}</span><span className="text-xs text-black/55">{copy.separateShipping}</span></div>
      <div className="space-y-4">{plan.shipments.map((shipment, index) => <article key={shipment.storeId} className="border border-black/15 bg-white"><div className="flex items-start justify-between gap-5 border-b border-black/10 p-5"><div className="flex min-w-0 gap-3"><span className="grid size-8 shrink-0 place-items-center bg-black text-[11px] text-white">{number(locale, index + 1)}</span><div><h3 className="font-semibold">{localize(shipment.storeName, locale, shipment.storeCode)}</h3>{shipment.address ? <p className="mt-1 text-xs leading-5 text-black/55"><MapPin className="me-1 inline size-3" />{localize(shipment.address, locale)}</p> : null}</div></div><div className="shrink-0 text-end"><small className="block text-[10px] text-black/50">{copy.shippingFee}</small><strong className="mt-1 block text-sm">{shipment.shippingMinor === 0 ? copy.free : formatMinor(shipment.shippingMinor, plan.currency, locale)}</strong></div></div><ul className="divide-y divide-black/10">{shipment.items.map((item, itemIndex) => <li key={`${item.variantId}:${item.locationId}:${itemIndex}`} className="flex items-center justify-between gap-4 px-5 py-3 text-xs"><span className="inline-flex min-w-0 items-center gap-2"><PackageCheck className="size-3.5 shrink-0 text-[#32644A]" /><span className="min-w-0"><strong className="block truncate">{localize(item.productName, locale, item.sku)}</strong><small className="mt-1 block truncate text-black/55">{localize(item.colorName, locale)} · {localize(item.sizeName, locale)} · {item.sku}</small></span></span><strong className="shrink-0">{copy.quantity}: {number(locale, item.quantity)}</strong></li>)}</ul></article>)}</div>
      <div className="mt-6 border-t-2 border-black bg-white p-5"><Money label={copy.itemsSubtotal} value={plan.subtotalMinor} currency={plan.currency} locale={locale} /><Money label={copy.shippingTotal} value={plan.shippingMinor} currency={plan.currency} locale={locale} /><div className="mt-3 border-t border-black/15 pt-3"><Money label={copy.grandTotal} value={plan.totalMinor} currency={plan.currency} locale={locale} strong /></div></div>
      <div className="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><Button type="button" variant="outline" disabled={confirming} onClick={onClose}>{copy.close}</Button><Button type="button" variant="black" loading={confirming} onClick={onConfirm}>{copy.confirmPlan}</Button></div>
    </>}</div>
  </div></div>, document.body);
}
function State({ text, children }: { text: string; children: React.ReactNode }) { return <div className="border-y border-black/15 bg-white px-6 py-12 text-center"><p className="text-sm leading-7">{text}</p><div className="mt-6 flex justify-center">{children}</div></div>; }
function Money({ label, value, currency, locale, strong }: { label: string; value: number; currency: string; locale: Locale; strong?: boolean }) { return <div className={`flex items-center justify-between gap-4 py-1 ${strong ? "text-base font-semibold" : "text-xs"}`}><span>{label}</span><span>{formatMinor(value, currency, locale)}</span></div>; }
export function localize(value: LocalizedText | null | undefined, locale: Locale, fallback = "") { return value?.[locale]?.trim() || value?.fa?.trim() || value?.en?.trim() || value?.ar?.trim() || fallback; }
function number(locale: Locale, value: number) { return new Intl.NumberFormat(locale === "fa" ? "fa-IR" : locale === "ar" ? "ar" : "en").format(value); }
