import type { Locale } from "@/lib/i18n/config";

const shared = {
  fa: { requested: "درخواستی", available: "موجود", orderSummary: "مرور سفارش", quantityLabel: "تعداد", itemsAmount: "مبلغ کالاها", deliveryPlan: "برنامه ارسال", modalTitle: "نحوه ارسال سفارش شما", modalDescription: "کالاها به‌صورت خودکار از کمترین تعداد شعبه موجود تخصیص داده شده‌اند. هر کارت یک مرسوله و هزینه ارسال مستقل است.", close: "بستن", loading: "در حال محاسبه موجودی و بهترین ترکیب شعبه‌ها…", retry: "تلاش دوباره", refresh: "محاسبه دوباره", loadError: "برنامه ارسال دریافت نشد.", noStoreAnywhere: "موجودی مجموع شعبه‌ها برای تکمیل این سبد کافی نیست.", shipments: "مرسوله", separateShipping: "هزینه هر مرسوله جدا محاسبه شده", shippingFee: "هزینه ارسال", free: "رایگان", quantity: "تعداد", itemsSubtotal: "جمع کالاها", shippingTotal: "جمع ارسال", grandTotal: "مبلغ نهایی", confirmPlan: "تأیید و رزرو موجودی", viewPlan: "مشاهده برنامه ارسال", ready: "برنامه ارسال آماده است", stockChanged: "موجودی، قیمت یا هزینه ارسال تغییر کرده است؛ برنامه جدید را دوباره تأیید کنید." },
  en: { requested: "Requested", available: "Available", orderSummary: "Order summary", quantityLabel: "Qty", itemsAmount: "Items amount", deliveryPlan: "Delivery plan", modalTitle: "How your order will be shipped", modalDescription: "Items are automatically allocated from the fewest available stores. Each card is a separate shipment with its own delivery fee.", close: "Close", loading: "Calculating inventory and the best store combination…", retry: "Try again", refresh: "Recalculate", loadError: "The delivery plan could not be loaded.", noStoreAnywhere: "Combined store inventory cannot currently fulfil this cart.", shipments: "shipments", separateShipping: "Each shipment is priced separately", shippingFee: "Delivery fee", free: "Free", quantity: "Qty", itemsSubtotal: "Items subtotal", shippingTotal: "Shipping total", grandTotal: "Grand total", confirmPlan: "Confirm and reserve", viewPlan: "View delivery plan", ready: "Your delivery plan is ready", stockChanged: "Inventory, prices or delivery fees changed. Please confirm the refreshed plan." },
  ar: { requested: "المطلوب", available: "المتوفر", orderSummary: "ملخص الطلب", quantityLabel: "الكمية", itemsAmount: "قيمة المنتجات", deliveryPlan: "خطة التوصيل", modalTitle: "طريقة شحن طلبك", modalDescription: "تُوزّع المنتجات تلقائياً على أقل عدد ممكن من الفروع. كل بطاقة شحنة مستقلة ورسومها منفصلة.", close: "إغلاق", loading: "جارٍ حساب المخزون وأفضل مجموعة فروع…", retry: "إعادة المحاولة", refresh: "إعادة الحساب", loadError: "تعذر تحميل خطة التوصيل.", noStoreAnywhere: "مخزون الفروع مجتمعة لا يكفي حالياً لإكمال السلة.", shipments: "شحنات", separateShipping: "تُحسب رسوم كل شحنة على حدة", shippingFee: "رسوم التوصيل", free: "مجاني", quantity: "الكمية", itemsSubtotal: "مجموع المنتجات", shippingTotal: "مجموع الشحن", grandTotal: "الإجمالي النهائي", confirmPlan: "تأكيد وحجز المخزون", viewPlan: "عرض خطة التوصيل", ready: "خطة التوصيل جاهزة", stockChanged: "تغير المخزون أو السعر أو رسم التوصيل. يرجى تأكيد الخطة المحدّثة." },
} as const;

export type CheckoutCopy = (typeof shared)[Locale];
export function getCheckoutCopy(locale: Locale) { return shared[locale]; }
