"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, Copy, Eye, Link2, Mail, RefreshCw, ShoppingBag, UserRound } from "lucide-react";
import { useMemo, useRef, useState } from "react";

import { useAdminTheme, getAdminDataThemeVars } from "@/components/admin/useAdminTheme";
import { DynamicDataTable } from "@/components/global/table/DynamicTable";
import { DynamicModal } from "@/components/global/table/DynamicModal";
import { DataButton, DataTextarea } from "@/components/global/table/primitives";
import type { DynamicColumn } from "@/components/global/table/types";
import { useToast } from "@/components/ui/CustomToast";
import { adminApi, DossierError, DossierLoading, ErrorBanner, faNumber, formatDate, Info, itemCount, ListResponse, LocalizedText, localized, Metric, Metrics, money, MoneyLine, OperationsHeader, StatusBadge, Timeline } from "@/components/admin/operations-ui";

type Recovery = "eligible" | "contacted" | "recovered" | "expired" | "suppressed";
type Reason = "inactivity" | "payment_failed" | "customer_left" | "reservation_expired";
type Item = { variantId: string; productName: LocalizedText; colorName: LocalizedText; sizeName: LocalizedText; quantity: number; unitPriceMinor: number };
type Abandoned = { _id: string; checkoutSessionId: string; cartId: string; userId?: string; anonymousId?: string; email?: string; storeId: string; cityId: string; currency: string; items: Item[]; subtotalMinor: number; abandonedAt: string; reason: Reason; recoveryStatus: Recovery; recoveryTokenCreatedAt?: string; recoveryTokenExpiresAt?: string; recoveryTokenUsedAt?: string; recoveryCartId?: string; recoveredOrderId?: string; recoveryCheckoutSessionId?: string; createdAt: string; updatedAt: string };
type RecoveryLinkResult = { abandonedCheckoutId: string; recoveryStatus: Recovery; expiresAt: string; recoveryUrl: string };
type Filters = Record<string, unknown> & { recoveryStatus: string | null; reason: string | null };
const STATUS: Record<Recovery, { label: string; tone: "good" | "warn" | "danger" | "info" | "neutral" }> = { eligible: { label: "واجد پیگیری", tone: "warn" }, contacted: { label: "تماس ثبت‌شده", tone: "info" }, recovered: { label: "بازیابی‌شده", tone: "good" }, expired: { label: "منقضی", tone: "neutral" }, suppressed: { label: "عدم پیگیری", tone: "danger" } };
const REASONS: Record<Reason, string> = { inactivity: "عدم فعالیت", payment_failed: "پرداخت ناموفق", customer_left: "ترک فرایند توسط مشتری", reservation_expired: "انقضای رزرو" };
const ACTIONS: Record<"contacted" | "suppressed" | "expired", { label: string; description: string; tone: "primary" | "warning" | "danger" }> = { contacted: { label: "ثبت تماس انجام‌شده", description: "فقط نتیجه یک ارتباط واقعی قبلی ثبت می‌شود؛ این دکمه پیام یا ایمیل ارسال نمی‌کند.", tone: "primary" }, suppressed: { label: "توقف پیگیری", description: "این رکورد از پیگیری‌های بعدی کنار گذاشته می‌شود.", tone: "warning" }, expired: { label: "بستن به‌عنوان منقضی", description: "پرونده به وضعیت نهایی منقضی می‌رود و دیگر قابل تغییر نیست.", tone: "danger" } };

export function AbandonedCheckoutsManager({ canWrite }: { canWrite: boolean }) {
  const theme = useAdminTheme(); const themeVars = useMemo(() => getAdminDataThemeVars(theme), [theme]); const queryClient = useQueryClient(); const [selectedId, setSelectedId] = useState<string | null>(null); const [listError, setListError] = useState<string | null>(null);
  const summary = useQuery({ queryKey: ["admin", "abandoned-checkouts", "summary"], queryFn: async ({ signal }) => { const states: Recovery[] = ["eligible", "contacted", "recovered"]; const [all, ...parts] = await Promise.all([adminApi<ListResponse<Abandoned>>("/api/admin/abandoned-checkouts?page=1&limit=1", { signal }), ...states.map((status) => adminApi<ListResponse<Abandoned>>(`/api/admin/abandoned-checkouts?page=1&limit=1&recoveryStatus=${status}`, { signal }))]); return { total: all.pagination.total, eligible: parts[0].pagination.total, contacted: parts[1].pagination.total, recovered: parts[2].pagination.total }; } });
  const refresh = () => void queryClient.invalidateQueries({ queryKey: ["admin", "abandoned-checkouts"] });
  const columns = useMemo<DynamicColumn<Abandoned>[]>(() => [
    { id: "contact", label: "مخاطب / پرونده", minWidth: 250, sticky: "start", lockVisibility: true, cell: ({ record }) => <button type="button" onClick={() => setSelectedId(record._id)} className="max-w-64 text-right text-[10px] font-bold text-[var(--adt-accent-strong)] hover:underline focus-visible:ring-2 focus-visible:ring-[var(--adt-accent)]/40"><span dir="ltr" className="block break-all text-left">{record.email || record.userId || record.anonymousId || "بدون تماس"}</span><span dir="ltr" className="mt-1 block break-all text-left text-[8px] text-[var(--adt-muted)]">{record._id}</span></button>, mobile: { priority: 1, showLabel: false } },
    { id: "recoveryStatus", label: "وضعیت بازیابی", accessor: "recoveryStatus", sortable: true, sortKey: "recoveryStatus", minWidth: 145, cell: ({ record }) => <StatusBadge {...STATUS[record.recoveryStatus]}/>, mobile: { priority: 2 } },
    { id: "reason", label: "علت رهاشدگی", accessor: "reason", minWidth: 150, cell: ({ record }) => REASONS[record.reason], mobile: { priority: 3 } },
    { id: "items", label: "اقلام", minWidth: 85, align: "center", cell: ({ record }) => `${faNumber.format(itemCount(record.items))} عدد`, mobile: { priority: 4 } },
    { id: "subtotalMinor", label: "جمع سبد", accessor: "subtotalMinor", sortable: true, sortKey: "subtotalMinor", minWidth: 165, cell: ({ record }) => <span dir="ltr" className="block text-left font-bold tabular-nums">{money(record.subtotalMinor, record.currency)}</span>, mobile: { priority: 5 } },
    { id: "destination", label: "شهر / شعبه", minWidth: 180, cell: ({ record }) => <span dir="ltr" className="block break-all text-left text-[9px]">{record.cityId}<br/><span className="text-[var(--adt-muted)]">{record.storeId}</span></span>, mobile: { hidden: true } },
    { id: "abandonedAt", label: "زمان رهاشدگی", accessor: "abandonedAt", sortable: true, sortKey: "abandonedAt", minWidth: 165, cell: ({ record }) => formatDate(record.abandonedAt), mobile: { priority: 6 } },
  ], []);
  return <div style={themeVars} className="min-w-0 space-y-3 p-3 text-[var(--adt-text)] sm:p-4 lg:p-5"><OperationsHeader eyebrow="بازیابی خرید" title="خریدهای رهاشده" description="داده سیستمی رهاشدگی را از ارتباط واقعی با مشتری جدا نگه دارید؛ این صفحه هیچ پیام، ایمیل یا پیشنهاد ساختگی ارسال نمی‌کند." onRefresh={refresh} refreshing={summary.isFetching}/><Metrics><Metric icon={<ShoppingBag size={17}/>} label="کل پرونده‌ها" value={summary.data?.total} loading={summary.isLoading} error={summary.isError}/><Metric icon={<RefreshCw size={17}/>} label="واجد پیگیری" value={summary.data?.eligible} loading={summary.isLoading} error={summary.isError}/><Metric icon={<Mail size={17}/>} label="تماس ثبت‌شده" value={summary.data?.contacted} loading={summary.isLoading} error={summary.isError}/><Metric icon={<UserRound size={17}/>} label="بازیابی‌شده" value={summary.data?.recovered} loading={summary.isLoading} error={summary.isError}/></Metrics><ErrorBanner message={summary.isError ? (summary.error instanceof Error ? summary.error.message : "خلاصه خریدهای رهاشده دریافت نشد.") : null}/><ErrorBanner message={listError ? `خطای فهرست: ${listError}` : null}/>
    <DynamicDataTable<Abandoned, Record<string, unknown>, Record<string, unknown>, Filters> tableId="admin-abandoned-checkouts" eyebrow="دفتر رهاشدگی" title="پرونده‌های خرید رهاشده" description="وضعیت بازیابی سیستمی، علت و اطلاعات دقیق ثبت‌شده محصول را بررسی کنید." source={{ queryKey: ["admin", "abandoned-checkouts", "list"], fetchPage: async ({ page, pageSize, search, sort, filters, signal }) => { const params = new URLSearchParams({ page: String(page), limit: String(pageSize) }); if (search) params.set("search", search); if (filters.recoveryStatus) params.set("recoveryStatus", String(filters.recoveryStatus)); if (filters.reason) params.set("reason", String(filters.reason)); if (sort[0]) { params.set("sortKey", sort[0].key); params.set("sortDirection", sort[0].direction); } setListError(null); try { const data = await adminApi<ListResponse<Abandoned>>(`/api/admin/abandoned-checkouts?${params}`, { signal }); return { items: data.items, total: data.pagination.total, pageCount: data.pagination.pages }; } catch (error) { if (!(error instanceof DOMException && error.name === "AbortError")) setListError(error instanceof Error ? error.message : "فهرست خریدهای رهاشده دریافت نشد."); throw error; } } }} columns={columns} getRowId={(record) => record._id} getRowLabel={(record) => record.email || record._id} search={{ placeholder: "جستجو با ایمیل، سبد، نشست خرید یا کاربر…", debounceMs: 320 }} filters={[{ id: "recoveryStatus", kind: "select", label: "وضعیت بازیابی", options: Object.entries(STATUS).map(([value, meta]) => ({ value, label: meta.label })), defaultValue: null }, { id: "reason", kind: "select", label: "علت رهاشدگی", options: Object.entries(REASONS).map(([value, label]) => ({ value, label })), defaultValue: null }]} initialFilters={{ recoveryStatus: null, reason: null }} pagination={{ initialPageSize: 15, pageSizeOptions: [10, 15, 25, 50], showPageNumbers: true }} columnVisibility={{ enabled: true, persist: true, storageKey: "admin-abandoned-columns" }} mobile={{ title: (record) => <span dir="ltr" className="block break-all whitespace-normal text-left">{record.email || record.userId || record.anonymousId || "مهمان"}</span>, badge: (record) => <StatusBadge {...STATUS[record.recoveryStatus]}/>, fieldIds: ["reason", "items", "subtotalMinor", "abandonedAt"], maxFields: 4 }} crud={{ extraRowActions: [{ id: "inspect", label: "مشاهده پرونده", icon: <Eye size={14}/>, onClick: (record) => setSelectedId(record._id) }] }} emptyState={{ title: "خرید رهاشده‌ای ثبت نشده است.", description: "رکوردهای واقعی پس از رهاشدگی یا انقضای رزرو اینجا نمایش داده می‌شوند.", filteredTitle: "پرونده‌ای با این شرایط پیدا نشد.", filteredDescription: "فیلتر یا جستجو را تغییر دهید." }}/><AbandonedDossier key={selectedId ?? "closed"} id={selectedId} canWrite={canWrite} onClose={() => setSelectedId(null)} onChanged={refresh}/>
  </div>;
}

function AbandonedDossier({ id, canWrite, onClose, onChanged }: { id: string | null; canWrite: boolean; onClose: () => void; onChanged: () => void }) {
  const queryClient = useQueryClient();
  const toast = useToast();
  const guard = useRef(false);
  const [action, setAction] = useState<keyof typeof ACTIONS | null>(null);
  const [actionTargetId, setActionTargetId] = useState<string | null>(null);
  const [reason, setReason] = useState("");
  const [showLinkForm, setShowLinkForm] = useState(false);
  const [linkReason, setLinkReason] = useState("");
  const [recoveryUrl, setRecoveryUrl] = useState("");
  const [copied, setCopied] = useState(false);
  const query = useQuery({ queryKey: ["admin", "abandoned-checkouts", "detail", id], queryFn: ({ signal }) => adminApi<Abandoned>(`/api/admin/abandoned-checkouts/${id}`, { signal }), enabled: Boolean(id) });
  const mutation = useMutation({ mutationFn: ({ id, recoveryStatus, reason }: { id: string; recoveryStatus: keyof typeof ACTIONS; reason: string }) => adminApi<Abandoned>(`/api/admin/abandoned-checkouts/${id}`, { method: "PATCH", body: JSON.stringify({ recoveryStatus, reason }) }), onSuccess: (record) => { queryClient.setQueryData(["admin", "abandoned-checkouts", "detail", record._id], record); toast.success("وضعیت پیگیری ثبت شد", { description: STATUS[record.recoveryStatus].label }); setAction(null); setActionTargetId(null); setReason(""); onChanged(); }, onSettled: () => { guard.current = false; } });
  const linkMutation = useMutation({ mutationFn: ({ id, reason }: { id: string; reason: string }) => adminApi<RecoveryLinkResult>(`/api/admin/abandoned-checkouts/${id}/recovery-link`, { method: "POST", body: JSON.stringify({ reason }) }), onSuccess: (result) => { if (result.abandonedCheckoutId !== id) return; setRecoveryUrl(result.recoveryUrl); setShowLinkForm(false); setLinkReason(""); setCopied(false); toast.success("لینک امن ساخته شد", { description: "لینک را دستی برای مشتری ارسال کنید." }); void query.refetch(); onChanged(); } });
  const record = query.data;
  const terminal = record ? ["recovered", "expired"].includes(record.recoveryStatus) : true;
  const linkEligible = Boolean(record?.userId && ["eligible", "contacted"].includes(record.recoveryStatus));
  const valid = reason.trim().length >= 3;
  const linkReasonValid = linkReason.trim().length >= 3;
  const close = () => { if (mutation.isPending || linkMutation.isPending || guard.current) return; setAction(null); setActionTargetId(null); setReason(""); setShowLinkForm(false); setLinkReason(""); setRecoveryUrl(""); setCopied(false); mutation.reset(); linkMutation.reset(); onClose(); };
  const confirmationValid = Boolean(action && record && id === record._id && actionTargetId === record._id && canWrite && !terminal);

  return <DynamicModal open={Boolean(id)} onClose={close} title="پرونده خرید رهاشده" description="اطلاعات دقیق ثبت‌شده خرید، هویت تماس و وضعیت بازیابی" size="xl" busy={mutation.isPending || linkMutation.isPending}>
    {query.isLoading ? <DossierLoading label="در حال دریافت پرونده رهاشدگی…"/> : null}
    {query.isError ? <DossierError error={query.error} retry={() => void query.refetch()}/> : null}
    {record ? <div className="space-y-4">
      <section className="grid gap-px border border-[var(--adt-border)] bg-[var(--adt-border)] sm:grid-cols-[1.15fr_.85fr]"><div className="min-w-0 bg-[var(--adt-surface)] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><StatusBadge {...STATUS[record.recoveryStatus]}/><span className="text-[9px] text-[var(--adt-muted)]">{REASONS[record.reason]}</span></div><h3 dir="ltr" className="mt-4 min-w-0 break-all text-left text-[17px] font-extrabold">{record.email || record.userId || record.anonymousId || "بدون اطلاعات تماس"}</h3></div><div className="bg-[var(--adt-surface-muted)] p-4"><small className="text-[9px] text-[var(--adt-muted)]">جمع اطلاعات ثبت‌شده</small><strong dir="ltr" className="mt-2 block text-left text-[20px] tabular-nums">{money(record.subtotalMinor, record.currency)}</strong><small className="mt-3 block text-[9px] text-[var(--adt-muted)]">{faNumber.format(itemCount(record.items))} کالا</small></div></section>
      <section><h3 className="mb-2 text-[12px] font-extrabold">اقلام ثبت‌شده در لحظه رهاشدگی</h3><div className="overflow-hidden border border-[var(--adt-border)]">{record.items.map((item, index) => <article key={`${item.variantId}-${index}`} className="grid min-w-0 gap-3 border-b border-[var(--adt-border)] p-3 last:border-b-0 sm:grid-cols-[minmax(0,1fr)_auto]"><div className="min-w-0"><strong className="text-[11px]">{localized(item.productName)}</strong><p className="mt-1 text-[9px] text-[var(--adt-muted)]">رنگ: {localized(item.colorName)} · سایز: {localized(item.sizeName)} · تعداد: {faNumber.format(item.quantity)}</p><p dir="ltr" className="mt-1 break-all text-left text-[9px] text-[var(--adt-muted)]">شناسه تنوع: {item.variantId}</p></div><div dir="ltr" className="min-w-0 text-left"><strong className="block tabular-nums">{money(item.unitPriceMinor * item.quantity, record.currency)}</strong><small className="mt-1 block text-[9px] text-[var(--adt-muted)]">قیمت واحد {money(item.unitPriceMinor, record.currency)}</small></div></article>)}</div></section>
      <section className="grid gap-px border border-[var(--adt-border)] bg-[var(--adt-border)]"><MoneyLine label="جمع اقلام" value={record.subtotalMinor} currency={record.currency}/></section>
      <section className="grid gap-3 border border-[var(--adt-border)] p-4 sm:grid-cols-2"><Info label="کاربر / مهمان" value={record.userId || record.anonymousId}/><Info label="ایمیل" value={record.email}/><Info label="سبد / نشست خرید" value={`${record.cartId} / ${record.checkoutSessionId}`}/><Info label="شهر / شعبه" value={`${record.cityId} / ${record.storeId}`}/><Info label="سبد بازیابی" value={record.recoveryCartId}/><Info label="سفارش بازیابی‌شده" value={record.recoveredOrderId}/></section>
      <section className="grid gap-3 border border-[var(--adt-border)] p-4 sm:grid-cols-3"><Timeline label="رهاشدگی" value={formatDate(record.abandonedAt)}/><Timeline label="ساخت لینک" value={formatDate(record.recoveryTokenCreatedAt)}/><Timeline label="انقضای لینک" value={formatDate(record.recoveryTokenExpiresAt)}/></section>

      <section className="border border-[var(--adt-border)] p-4">
        <div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="flex items-center gap-2 text-[12px] font-extrabold"><Link2 size={15}/>لینک امن بازیابی</h3><p className="mt-1 text-[9px] leading-5 text-[var(--adt-muted)]">هیچ پیامک یا ایمیلی خودکار ارسال نمی‌شود؛ لینک را فقط به مشتری صاحب حساب بدهید.</p></div>{record.userId ? <StatusBadge label="مشتری احراز‌شده" tone="good"/> : <StatusBadge label="مهمان؛ غیرقابل بازیابی" tone="danger"/>}</div>
        {canWrite && linkEligible && !recoveryUrl && !showLinkForm ? <DataButton className="mt-4" tone="primary" disabled={linkMutation.isPending} onClick={() => { setAction(null); setActionTargetId(null); setReason(""); setShowLinkForm(true); setLinkReason(""); linkMutation.reset(); }}>ساخت / نوسازی لینک بازیابی</DataButton> : null}
        {showLinkForm && linkEligible && id === record._id ? <div className="mt-4 border border-[var(--adt-warning)]/35 bg-[var(--adt-warning)]/[0.06] p-4"><strong className="text-[11px]">تأیید نوسازی لینک</strong><p className="mt-2 text-[9px] leading-5">لینک قبلی فوراً نامعتبر می‌شود. دلیل عملیاتی را ثبت کنید.</p><DataTextarea autoFocus className="mt-3" label="دلیل ساخت یا نوسازی" required maxLength={300} disabled={linkMutation.isPending} value={linkReason} onChange={(event) => setLinkReason(event.target.value)} error={linkReason.length > 0 && !linkReasonValid ? "حداقل ۳ نویسه وارد کنید." : undefined}/>{linkMutation.isError ? <p role="alert" className="mt-3 text-[10px] text-[var(--adt-danger)]">{linkMutation.error instanceof Error ? linkMutation.error.message : "ساخت لینک انجام نشد."}</p> : null}<div className="mt-4 flex justify-end gap-2"><DataButton disabled={linkMutation.isPending} onClick={() => { setShowLinkForm(false); setLinkReason(""); linkMutation.reset(); }}>انصراف</DataButton><DataButton tone="primary" loading={linkMutation.isPending} disabled={!linkReasonValid} onClick={() => { if (!id || id !== record._id || !linkEligible || !linkReasonValid || linkMutation.isPending) return; linkMutation.mutate({ id: record._id, reason: linkReason.trim() }); }}>تأیید و ساخت لینک</DataButton></div></div> : null}
        {recoveryUrl ? <div className="mt-4 border border-[var(--adt-success)]/35 bg-[var(--adt-success)]/[0.06] p-4"><div className="flex items-center gap-2"><Check size={15}/><strong className="text-[11px]">لینک فقط همین‌بار نمایش داده می‌شود</strong></div><p dir="ltr" className="mt-3 max-h-20 overflow-auto break-all border border-[var(--adt-border)] bg-[var(--adt-surface)] p-3 text-left text-[9px] leading-5">{recoveryUrl}</p><div className="mt-3 flex justify-end"><DataButton tone="primary" onClick={async () => { try { await navigator.clipboard.writeText(recoveryUrl); setCopied(true); toast.success("لینک کپی شد"); } catch { toast.error("کپی خودکار انجام نشد", { description: "لینک را به‌صورت دستی انتخاب و کپی کنید." }); } }}>{copied ? <Check size={14}/> : <Copy size={14}/>} {copied ? "کپی شد" : "کپی لینک"}</DataButton></div></div> : null}
        {!linkEligible && !recoveryUrl ? <p className="mt-4 text-[10px] leading-5 text-[var(--adt-muted)]">{!record.userId ? "تا زمان فعال‌شدن احراز هویت پیامکی، برای خرید مهمان لینک ساخته نمی‌شود." : "وضعیت این پرونده اجازه ساخت لینک تازه را نمی‌دهد."}</p> : null}
      </section>

      <section className="border border-[var(--adt-border)] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-[12px] font-extrabold">ثبت نتیجه پیگیری</h3><p className="mt-1 text-[9px] leading-5 text-[var(--adt-muted)]">وضعیت «بازیابی‌شده» فقط توسط خرید موفق سیستم تعیین می‌شود.</p></div>{!canWrite ? <StatusBadge label="فقط مشاهده" tone="warn"/> : null}</div>{canWrite && !terminal ? <div className="mt-4 flex flex-wrap gap-2">{(Object.keys(ACTIONS) as Array<keyof typeof ACTIONS>).map((key) => <DataButton key={key} tone={ACTIONS[key].tone} disabled={mutation.isPending || linkMutation.isPending} onClick={() => { if (!guard.current) { setShowLinkForm(false); setLinkReason(""); setRecoveryUrl(""); setAction(key); setActionTargetId(record._id); setReason(""); mutation.reset(); } }}>{ACTIONS[key].label}</DataButton>)}</div> : <p className="mt-4 text-[10px] text-[var(--adt-muted)]">{terminal ? "این پرونده نهایی است و قابل تغییر نیست." : "اجازه ثبت نتیجه پیگیری را ندارید."}</p>}{action && confirmationValid ? <div className="mt-4 border border-[var(--adt-warning)]/35 bg-[var(--adt-warning)]/[0.06] p-4"><strong>{ACTIONS[action].label}</strong><p className="mt-2 text-[10px] leading-6">{ACTIONS[action].description}</p><DataTextarea autoFocus className="mt-3" label="دلیل و مستند عملیاتی" required maxLength={300} disabled={mutation.isPending} value={reason} onChange={(event) => setReason(event.target.value)} error={reason.length > 0 && !valid ? "حداقل ۳ نویسه وارد کنید." : undefined}/>{mutation.isError ? <p role="alert" className="mt-3 text-[10px] text-[var(--adt-danger)]">{mutation.error instanceof Error ? mutation.error.message : "عملیات انجام نشد."}</p> : null}<div className="mt-4 flex justify-end gap-2"><DataButton disabled={mutation.isPending} onClick={() => { setAction(null); setActionTargetId(null); setReason(""); mutation.reset(); }}>انصراف</DataButton><DataButton tone={ACTIONS[action].tone} loading={mutation.isPending} disabled={!valid} onClick={() => { if (!valid || !confirmationValid || !record || guard.current || mutation.isPending) return; guard.current = true; mutation.mutate({ id: record._id, recoveryStatus: action, reason: reason.trim() }); }}>تأیید و ثبت</DataButton></div></div> : null}</section>
    </div> : null}
  </DynamicModal>;
}
