"use client";

import { useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, Eye, ScrollText, ShieldAlert, UserRound } from "lucide-react";
import { useMemo, useState } from "react";

import { useAdminTheme, getAdminDataThemeVars } from "@/components/admin/useAdminTheme";
import { DynamicDataTable } from "@/components/global/table/DynamicTable";
import { DynamicModal } from "@/components/global/table/DynamicModal";
import type { DynamicColumn, PersianDateRangeValue } from "@/components/global/table/types";
import { adminApi, ErrorBanner, formatDate, Info, ListResponse, Metric, Metrics, OperationsHeader, StatusBadge, Timeline } from "@/components/admin/operations-ui";

type Outcome = "success" | "failure";
type Audit = { _id: string; userId?: string; email?: string; action: string; outcome: Outcome; sessionId?: string; ipAddress?: string; userAgent?: string; reason?: string; targetType?: string; targetId?: string; createdAt: string; updatedAt: string };
type Filters = Record<string, unknown> & { outcome: string | null; action: string | null; targetType: string | null; range: PersianDateRangeValue };
const OUTCOME = { success: { label: "موفق", tone: "good" as const }, failure: { label: "ناموفق", tone: "danger" as const } };

function startIso(value: string) { const date = new Date(value); date.setHours(0, 0, 0, 0); return date.toISOString(); }
function endIso(value: string) { const date = new Date(value); date.setHours(23, 59, 59, 999); return date.toISOString(); }

export function AuditManager() {
  const theme = useAdminTheme(); const themeVars = useMemo(() => getAdminDataThemeVars(theme), [theme]); const queryClient = useQueryClient(); const [selected, setSelected] = useState<Audit | null>(null); const [listError, setListError] = useState<string | null>(null);
  const summary = useQuery({ queryKey: ["admin", "audit", "summary"], queryFn: async ({ signal }) => { const [all, success, failure] = await Promise.all([adminApi<ListResponse<Audit>>("/api/admin/audit?page=1&limit=1", { signal }), adminApi<ListResponse<Audit>>("/api/admin/audit?page=1&limit=1&outcome=success", { signal }), adminApi<ListResponse<Audit>>("/api/admin/audit?page=1&limit=1&outcome=failure", { signal })]); return { total: all.pagination.total, success: success.pagination.total, failure: failure.pagination.total }; } });
  const refresh = () => void queryClient.invalidateQueries({ queryKey: ["admin", "audit"] });
  const columns = useMemo<DynamicColumn<Audit>[]>(() => [
    { id: "action", label: "رویداد", accessor: "action", minWidth: 220, sticky: "start", lockVisibility: true, cell: ({ record }) => <button type="button" onClick={() => setSelected(record)} dir="ltr" className="block max-w-64 break-all text-left text-[10px] font-bold text-[var(--adt-accent-strong)] hover:underline focus-visible:ring-2 focus-visible:ring-[var(--adt-accent)]/40">{record.action}</button>, mobile: { priority: 1, showLabel: false } },
    { id: "outcome", label: "نتیجه", accessor: "outcome", minWidth: 100, cell: ({ record }) => <StatusBadge {...OUTCOME[record.outcome]}/>, mobile: { priority: 2 } },
    { id: "actor", label: "عامل", minWidth: 210, cell: ({ record }) => <span dir="ltr" className="block break-all text-left text-[9px] leading-5"><b>{record.email || "بدون ایمیل"}</b><br/><span className="text-[var(--adt-muted)]">{record.userId || "عامل سیستمی"}</span></span>, mobile: { priority: 3 } },
    { id: "target", label: "هدف", minWidth: 220, cell: ({ record }) => <span dir="ltr" className="block break-all text-left text-[9px] leading-5">{record.targetType || "—"}<br/><span className="text-[var(--adt-muted)]">{record.targetId || "—"}</span></span>, mobile: { priority: 4 } },
    { id: "reason", label: "دلیل", accessor: "reason", minWidth: 240, cell: ({ record }) => <span className="line-clamp-2 text-[9px] leading-5">{record.reason || "—"}</span>, mobile: { hidden: true } },
    { id: "createdAt", label: "زمان رویداد", accessor: "createdAt", minWidth: 170, cell: ({ record }) => formatDate(record.createdAt), mobile: { priority: 5 } },
  ], []);
  return <div style={themeVars} className="min-w-0 space-y-3 p-3 text-[var(--adt-text)] sm:p-4 lg:p-5"><OperationsHeader eyebrow="امنیت و رهگیری" title="تاریخچه تغییرناپذیر ممیزی" description="رویدادهای کارکنان و سیستم را با عامل، نتیجه، هدف و مشخصات نشست بررسی کنید. هیچ رکوردی از این صفحه قابل ویرایش یا حذف نیست." onRefresh={refresh} refreshing={summary.isFetching}/><Metrics><Metric icon={<ScrollText size={17}/>} label="کل رویدادها" value={summary.data?.total} loading={summary.isLoading} error={summary.isError}/><Metric icon={<CheckCircle2 size={17}/>} label="موفق" value={summary.data?.success} loading={summary.isLoading} error={summary.isError}/><Metric icon={<ShieldAlert size={17}/>} label="ناموفق" value={summary.data?.failure} loading={summary.isLoading} error={summary.isError}/><Metric icon={<UserRound size={17}/>} label="ثبت تغییرناپذیر" value={summary.data?.total} loading={summary.isLoading} error={summary.isError}/></Metrics><ErrorBanner message={summary.isError ? (summary.error instanceof Error ? summary.error.message : "خلاصه ممیزی دریافت نشد.") : null}/><ErrorBanner message={listError ? `خطای فهرست: ${listError}` : null}/>
    <DynamicDataTable<Audit, Record<string, unknown>, Record<string, unknown>, Filters> tableId="admin-audit" eyebrow="دفتر ممیزی" title="خط زمانی عملیات" description="فیلترهای تاریخ، نتیجه، نوع هدف و نام اقدام روی داده واقعی اعمال می‌شوند." source={{ queryKey: ["admin", "audit", "list"], fetchPage: async ({ page, pageSize, search, filters, signal }) => { const params = new URLSearchParams({ page: String(page), limit: String(pageSize) }); if (search) params.set("search", search); if (filters.outcome) params.set("outcome", String(filters.outcome)); if (filters.action) params.set("action", String(filters.action)); if (filters.targetType) params.set("targetType", String(filters.targetType)); const range = filters.range; if (range?.from) params.set("from", startIso(range.from)); if (range?.to) params.set("to", endIso(range.to)); setListError(null); try { const data = await adminApi<ListResponse<Audit>>(`/api/admin/audit?${params}`, { signal }); return { items: data.items, total: data.pagination.total, pageCount: data.pagination.pages }; } catch (error) { if (!(error instanceof DOMException && error.name === "AbortError")) setListError(error instanceof Error ? error.message : "تاریخچه ممیزی دریافت نشد."); throw error; } } }} columns={columns} getRowId={(record) => record._id} getRowLabel={(record) => record.action} search={{ placeholder: "جستجو در ایمیل، اقدام، دلیل یا شناسه هدف…", debounceMs: 320 }} filters={[{ id: "outcome", kind: "select", label: "نتیجه", options: [{ value: "success", label: "موفق" }, { value: "failure", label: "ناموفق" }], defaultValue: null }, { id: "action", kind: "text", label: "نام دقیق اقدام", placeholder: "مثلاً order.cancel", defaultValue: null }, { id: "targetType", kind: "text", label: "نوع دقیق هدف", placeholder: "مثلاً order", defaultValue: null }, { id: "range", kind: "date-range", label: "بازه زمانی", defaultValue: { from: null, to: null } }]} initialFilters={{ outcome: null, action: null, targetType: null, range: { from: null, to: null } }} pagination={{ initialPageSize: 30, pageSizeOptions: [15, 30, 50, 100], showPageNumbers: true }} columnVisibility={{ enabled: true, persist: true, storageKey: "admin-audit-columns" }} mobile={{ title: (record) => record.action, subtitle: (record) => record.email || record.userId || "عامل سیستمی", badge: (record) => <StatusBadge {...OUTCOME[record.outcome]}/>, fieldIds: ["actor", "target", "createdAt"], maxFields: 3 }} crud={{ extraRowActions: [{ id: "inspect", label: "مشاهده جزئیات", icon: <Eye size={14}/>, onClick: setSelected }] }} emptyState={{ title: "رویداد ممیزی وجود ندارد.", description: "با انجام عملیات کارکنان، رویدادها به‌صورت تغییرناپذیر ثبت می‌شوند.", filteredTitle: "رویدادی با این فیلترها پیدا نشد.", filteredDescription: "بازه یا فیلترها را تغییر دهید." }}/><AuditDossier record={selected} onClose={() => setSelected(null)}/>
  </div>;
}

function AuditDossier({ record, onClose }: { record: Audit | null; onClose: () => void }) {
  return <DynamicModal open={Boolean(record)} onClose={onClose} title="جزئیات رویداد ممیزی" description="رکورد تغییرناپذیر عامل، هدف و محیط درخواست" size="lg">{record ? <div className="space-y-4"><section className="border border-[var(--adt-border)] bg-[var(--adt-surface)] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><StatusBadge {...OUTCOME[record.outcome]}/><span dir="ltr" className="break-all text-left text-[9px] text-[var(--adt-muted)]">{record._id}</span></div><h3 dir="ltr" className="mt-4 break-all text-left text-[17px] font-extrabold">{record.action}</h3><p className="mt-3 text-[10px] leading-6 text-[var(--adt-muted)]">{record.reason || "دلیلی برای این رویداد ثبت نشده است."}</p></section><section className="grid gap-3 border border-[var(--adt-border)] p-4 sm:grid-cols-2"><Info label="ایمیل عامل" value={record.email}/><Info label="شناسه عامل" value={record.userId}/><Info label="نوع هدف" value={record.targetType}/><Info label="شناسه هدف" value={record.targetId}/><Info label="شناسه نشست" value={record.sessionId}/><Info label="نشانی اینترنتی" value={record.ipAddress}/></section><section className="border border-[var(--adt-border)] p-4"><Info label="مشخصات مرورگر و دستگاه" value={record.userAgent}/></section><section className="grid gap-3 border border-[var(--adt-border)] p-4 sm:grid-cols-2"><Timeline label="زمان ثبت" value={formatDate(record.createdAt)}/><Timeline label="آخرین نگارش" value={formatDate(record.updatedAt)}/></section><section className="border-r-2 border-[var(--adt-accent)] bg-[var(--adt-surface-muted)] p-4 text-[10px] leading-6"><strong>رکورد ممیزی فقط‌خواندنی و تغییرناپذیر است.</strong></section></div> : null}</DynamicModal>;
}
