"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Ban, Boxes, Clock3, Eye, ShoppingCart, UserRound } from "lucide-react";
import { useMemo, useRef, useState } from "react";

import { DynamicDataTable } from "@/components/global/table/DynamicTable";
import { DynamicModal } from "@/components/global/table/DynamicModal";
import { DataButton, DataTextarea } from "@/components/global/table/primitives";
import type { DynamicColumn } from "@/components/global/table/types";
import { useToast } from "@/components/ui/CustomToast";
import { useAdminTheme, getAdminDataThemeVars } from "@/components/admin/useAdminTheme";
import { adminApi, DossierError, DossierLoading, ErrorBanner, faNumber, formatDate, Info, itemCount, ListResponse, Metric, Metrics, money, MoneyLine, OperationsHeader, StatusBadge, Timeline } from "@/components/admin/operations-ui";

type CartStatus = "active" | "checkout_started" | "converted" | "abandoned" | "expired";
type CartAction = "mark_abandoned" | "expire";
type CartItem = { _id: string; variantId: string; quantity: number; unitPriceMinor: number; addedAt: string };
type Cart = { _id: string; userId?: string; anonymousId?: string; storeId?: string; cityId?: string; currency: string; items: CartItem[]; status: CartStatus; expiresAt: string; createdAt: string; updatedAt: string };
type Filters = Record<string, unknown> & { status: string | null };

const STATUS: Record<CartStatus, { label: string; tone: "good" | "warn" | "danger" | "info" | "neutral" }> = { active: { label: "فعال", tone: "good" }, checkout_started: { label: "خرید آغازشده", tone: "info" }, converted: { label: "تبدیل‌شده", tone: "good" }, abandoned: { label: "رهاشده", tone: "warn" }, expired: { label: "منقضی", tone: "neutral" } };
const ACTIONS: Record<CartAction, { label: string; effect: string }> = { mark_abandoned: { label: "ثبت به‌عنوان رهاشده", effect: "سبد از چرخه فعال خارج و برای پیگیری رهاشدگی ثبت می‌شود." }, expire: { label: "منقضی‌کردن سبد", effect: "سبد فوراً منقضی می‌شود و ادامه خرید با آن ممکن نخواهد بود." } };
const total = (cart: Cart) => cart.items.reduce((sum, item) => sum + item.unitPriceMinor * item.quantity, 0);
const identity = (cart: Cart) => cart.userId ? `کاربر ${cart.userId}` : `مهمان ${cart.anonymousId || "—"}`;

export function CartsManager({ canWrite }: { canWrite: boolean }) {
  const theme = useAdminTheme(); const themeVars = useMemo(() => getAdminDataThemeVars(theme), [theme]); const queryClient = useQueryClient();
  const [selectedId, setSelectedId] = useState<string | null>(null); const [listError, setListError] = useState<string | null>(null);
  const summary = useQuery({ queryKey: ["admin", "carts", "summary"], queryFn: async ({ signal }) => { const states: CartStatus[] = ["active", "checkout_started", "abandoned"]; const [all, ...parts] = await Promise.all([adminApi<ListResponse<Cart>>("/api/admin/carts?page=1&limit=1", { signal }), ...states.map((status) => adminApi<ListResponse<Cart>>(`/api/admin/carts?page=1&limit=1&status=${status}`, { signal }))]); return { total: all.pagination.total, active: parts[0].pagination.total, checkout: parts[1].pagination.total, abandoned: parts[2].pagination.total }; } });
  const refresh = () => void queryClient.invalidateQueries({ queryKey: ["admin", "carts"] });
  const columns = useMemo<DynamicColumn<Cart>[]>(() => [
    { id: "identity", label: "هویت سبد", minWidth: 245, sticky: "start", lockVisibility: true, cell: ({ record }) => <button type="button" onClick={() => setSelectedId(record._id)} className="max-w-64 whitespace-normal text-right text-[10px] font-bold text-[var(--adt-accent-strong)] hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--adt-accent)]/40"><span dir="ltr" className="block break-all whitespace-normal text-left">{identity(record)}</span><span dir="ltr" className="mt-1 block break-all whitespace-normal text-left text-[8px] text-[var(--adt-muted)]">{record._id}</span></button>, mobile: { priority: 1, showLabel: false } },
    { id: "status", label: "وضعیت", accessor: "status", sortable: true, sortKey: "status", minWidth: 130, cell: ({ record }) => <StatusBadge {...STATUS[record.status]}/>, mobile: { priority: 2 } },
    { id: "items", label: "اقلام", minWidth: 90, align: "center", cell: ({ record }) => `${faNumber.format(itemCount(record.items))} عدد`, mobile: { priority: 3 } },
    { id: "subtotal", label: "جمع سبد", minWidth: 160, cell: ({ record }) => <span dir="ltr" className="block text-left font-bold tabular-nums">{money(total(record), record.currency)}</span>, mobile: { priority: 4 } },
    { id: "destination", label: "شهر / شعبه", minWidth: 190, cell: ({ record }) => <span dir="ltr" className="block break-all text-left text-[9px] leading-5">{record.cityId || "—"}<br/><span className="text-[var(--adt-muted)]">{record.storeId || "—"}</span></span>, mobile: { hidden: true } },
    { id: "expiresAt", label: "انقضا", accessor: "expiresAt", sortable: true, sortKey: "expiresAt", minWidth: 160, cell: ({ record }) => formatDate(record.expiresAt), mobile: { priority: 5 } },
    { id: "updatedAt", label: "آخرین تغییر", accessor: "updatedAt", sortable: true, sortKey: "updatedAt", minWidth: 160, cell: ({ record }) => formatDate(record.updatedAt), mobile: { hidden: true } },
  ], []);
  return <div style={themeVars} className="min-w-0 space-y-3 p-3 text-[var(--adt-text)] sm:p-4 lg:p-5">
    <OperationsHeader eyebrow="عملیات سبد" title="مرکز سبدهای خرید" description="سبدهای کاربران و مهمان‌ها، مقصد انتخابی و اقلام دقیق را بررسی کنید؛ تغییر وضعیت فقط برای سبدهای در جریان مجاز است." onRefresh={refresh} refreshing={summary.isFetching}/>
    <Metrics><Metric icon={<ShoppingCart size={17}/>} label="کل سبدها" value={summary.data?.total} loading={summary.isLoading} error={summary.isError}/><Metric icon={<Boxes size={17}/>} label="فعال" value={summary.data?.active} loading={summary.isLoading} error={summary.isError}/><Metric icon={<Clock3 size={17}/>} label="در فرایند خرید" value={summary.data?.checkout} loading={summary.isLoading} error={summary.isError}/><Metric icon={<Ban size={17}/>} label="رهاشده" value={summary.data?.abandoned} loading={summary.isLoading} error={summary.isError}/></Metrics>
    <ErrorBanner message={summary.isError ? (summary.error instanceof Error ? summary.error.message : "خلاصه سبدها دریافت نشد.") : null}/><ErrorBanner message={listError ? `خطای فهرست: ${listError}` : null}/>
    <DynamicDataTable<Cart, Record<string, unknown>, Record<string, unknown>, Filters> tableId="admin-carts" eyebrow="دفتر سبدها" title="دفتر سبدهای خرید" description="برای مشاهده جزئیات دقیق و اقدامات مجاز، هویت سبد را انتخاب کنید." source={{ queryKey: ["admin", "carts", "list"], fetchPage: async ({ page, pageSize, search, sort, filters, signal }) => { const params = new URLSearchParams({ page: String(page), limit: String(pageSize) }); if (search) params.set("search", search); if (filters.status) params.set("status", String(filters.status)); if (sort[0]) { params.set("sortKey", sort[0].key); params.set("sortDirection", sort[0].direction); } setListError(null); try { const data = await adminApi<ListResponse<Cart>>(`/api/admin/carts?${params}`, { signal }); return { items: data.items, total: data.pagination.total, pageCount: data.pagination.pages }; } catch (error) { if (!(error instanceof DOMException && error.name === "AbortError")) setListError(error instanceof Error ? error.message : "فهرست سبدها دریافت نشد."); throw error; } } }} columns={columns} getRowId={(record) => record._id} getRowLabel={identity} search={{ placeholder: "جستجو با شناسه کاربر یا مهمان…", debounceMs: 320 }} filters={[{ id: "status", kind: "select", label: "وضعیت سبد", options: Object.entries(STATUS).map(([value, meta]) => ({ value, label: meta.label })), defaultValue: null }]} initialFilters={{ status: null }} pagination={{ initialPageSize: 15, pageSizeOptions: [10, 15, 25, 50], showPageNumbers: true }} columnVisibility={{ enabled: true, persist: true, storageKey: "admin-carts-columns" }} mobile={{ title: (record) => <span dir="ltr" className="block break-all whitespace-normal text-left">{identity(record)}</span>, badge: (record) => <StatusBadge {...STATUS[record.status]}/>, fieldIds: ["items", "subtotal", "expiresAt"], maxFields: 3 }} crud={{ extraRowActions: [{ id: "inspect", label: "مشاهده پرونده", icon: <Eye size={14}/>, onClick: (record) => setSelectedId(record._id) }] }} emptyState={{ title: "سبدی ثبت نشده است.", description: "سبدهای واقعی مشتریان اینجا نمایش داده می‌شوند.", filteredTitle: "سبدی با این شرایط پیدا نشد.", filteredDescription: "فیلتر یا عبارت جستجو را تغییر دهید." }}/>
    <CartDossier key={selectedId ?? "closed"} cartId={selectedId} canWrite={canWrite} onClose={() => setSelectedId(null)} onChanged={refresh}/>
  </div>;
}

function CartDossier({ cartId, canWrite, onClose, onChanged }: { cartId: string | null; canWrite: boolean; onClose: () => void; onChanged: () => void }) {
  const queryClient = useQueryClient(); const toast = useToast(); const guard = useRef(false); const [action, setAction] = useState<CartAction | null>(null); const [actionTargetId, setActionTargetId] = useState<string | null>(null); const [reason, setReason] = useState("");
  const query = useQuery({ queryKey: ["admin", "carts", "detail", cartId], queryFn: ({ signal }) => adminApi<Cart>(`/api/admin/carts/${cartId}`, { signal }), enabled: Boolean(cartId) });
  const mutation = useMutation({ mutationFn: ({ id, action, reason }: { id: string; action: CartAction; reason: string }) => adminApi<Cart>(`/api/admin/carts/${id}`, { method: "PATCH", body: JSON.stringify({ action, reason }) }), onSuccess: (cart) => { queryClient.setQueryData(["admin", "carts", "detail", cart._id], cart); toast.success("وضعیت سبد ثبت شد", { description: STATUS[cart.status].label }); setAction(null); setActionTargetId(null); setReason(""); onChanged(); }, onSettled: () => { guard.current = false; } });
  const cart = query.data; const actionable = cart && ["active", "checkout_started"].includes(cart.status); const valid = reason.trim().length >= 3;
  const close = () => { if (mutation.isPending || guard.current) return; setAction(null); setActionTargetId(null); setReason(""); mutation.reset(); onClose(); };
  const confirmationValid = Boolean(action && cart && cartId === cart._id && actionTargetId === cart._id && canWrite && actionable);
  return <DynamicModal open={Boolean(cartId)} onClose={close} title="پرونده عملیاتی سبد" description="هویت، اقلام دقیق، مقصد و زمان‌بندی سبد" size="xl" busy={mutation.isPending}>
    {query.isLoading ? <DossierLoading label="در حال دریافت پرونده سبد…"/> : null}{query.isError ? <DossierError error={query.error} retry={() => void query.refetch()}/> : null}
    {cart ? <div className="space-y-4"><section className="grid gap-px border border-[var(--adt-border)] bg-[var(--adt-border)] sm:grid-cols-[1.15fr_.85fr]"><div className="min-w-0 bg-[var(--adt-surface)] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><StatusBadge {...STATUS[cart.status]}/><span dir="ltr" className="break-all text-left text-[9px] text-[var(--adt-muted)]">{cart._id}</span></div><h3 dir="ltr" className="mt-4 min-w-0 break-all text-left text-[17px] font-extrabold">{identity(cart)}</h3></div><div className="bg-[var(--adt-surface-muted)] p-4"><small className="text-[9px] text-[var(--adt-muted)]">جمع سبد</small><strong dir="ltr" className="mt-2 block text-left text-[20px] tabular-nums">{money(total(cart), cart.currency)}</strong><small className="mt-3 block text-[9px] text-[var(--adt-muted)]">{faNumber.format(itemCount(cart.items))} کالا</small></div></section>
      <section><h3 className="mb-2 text-[12px] font-extrabold">اقلام و تنوع‌های دقیق</h3><div className="overflow-hidden border border-[var(--adt-border)]">{cart.items.map((item) => <article key={item._id} className="grid min-w-0 gap-3 border-b border-[var(--adt-border)] p-3 last:border-b-0 sm:grid-cols-[minmax(0,1fr)_auto]"><div className="min-w-0"><strong>تعداد {faNumber.format(item.quantity)}</strong><p dir="ltr" className="mt-1 break-all text-left text-[9px] text-[var(--adt-muted)]">شناسه تنوع: {item.variantId}</p><p className="mt-1 text-[9px] text-[var(--adt-muted)]">افزوده‌شده: {formatDate(item.addedAt)}</p></div><div dir="ltr" className="min-w-0 text-left"><strong className="block tabular-nums">{money(item.unitPriceMinor * item.quantity, cart.currency)}</strong><small className="mt-1 block text-[9px] text-[var(--adt-muted)]">قیمت واحد {money(item.unitPriceMinor, cart.currency)}</small></div></article>)}</div></section>
      <section className="grid gap-px border border-[var(--adt-border)] bg-[var(--adt-border)]"><MoneyLine label="جمع اقلام" value={total(cart)} currency={cart.currency}/></section>
      <section className="grid gap-3 border border-[var(--adt-border)] p-4 sm:grid-cols-2"><Info icon={<UserRound size={14}/>} label="شناسه کاربر" value={cart.userId}/><Info label="شناسه مهمان" value={cart.anonymousId}/><Info label="شهر" value={cart.cityId}/><Info label="شعبه" value={cart.storeId}/></section>
      <section className="grid gap-3 border border-[var(--adt-border)] p-4 sm:grid-cols-3"><Timeline label="ایجاد" value={formatDate(cart.createdAt)}/><Timeline label="آخرین تغییر" value={formatDate(cart.updatedAt)}/><Timeline label="انقضا" value={formatDate(cart.expiresAt)}/></section>
      <section className="border border-[var(--adt-border)] p-4"><div className="flex items-center justify-between gap-3"><div><h3 className="text-[12px] font-extrabold">اقدام قانونی بعدی</h3><p className="mt-1 text-[9px] text-[var(--adt-muted)]">این اقدامات ارتباطی با مشتری ارسال نمی‌کنند و در ممیزی ثبت می‌شوند.</p></div>{!canWrite ? <StatusBadge label="فقط مشاهده" tone="warn"/> : null}</div>{canWrite && actionable ? <div className="mt-4 flex flex-wrap gap-2">{(Object.keys(ACTIONS) as CartAction[]).map((key) => <DataButton key={key} tone={key === "expire" ? "danger" : "warning"} disabled={mutation.isPending} onClick={() => { if (!guard.current) { setAction(key); setActionTargetId(cart._id); setReason(""); mutation.reset(); } }}>{ACTIONS[key].label}</DataButton>)}</div> : <p className="mt-4 text-[10px] text-[var(--adt-muted)]">برای وضعیت فعلی اقدام دستی مجاز نیست.</p>}
        {action && confirmationValid ? <div className="mt-4 border border-[var(--adt-warning)]/35 bg-[var(--adt-warning)]/[0.06] p-4"><strong>{ACTIONS[action].label}</strong><p className="mt-2 text-[10px] leading-6">{ACTIONS[action].effect}</p><DataTextarea autoFocus className="mt-3" label="دلیل عملیاتی" required maxLength={300} disabled={mutation.isPending} value={reason} onChange={(event) => setReason(event.target.value)} error={reason.length > 0 && !valid ? "حداقل ۳ نویسه وارد کنید." : undefined}/>{mutation.isError ? <p role="alert" className="mt-3 text-[10px] text-[var(--adt-danger)]">{mutation.error instanceof Error ? mutation.error.message : "عملیات انجام نشد."}</p> : null}<div className="mt-4 flex justify-end gap-2"><DataButton disabled={mutation.isPending} onClick={() => { setAction(null); setActionTargetId(null); setReason(""); mutation.reset(); }}>انصراف</DataButton><DataButton tone={action === "expire" ? "danger" : "warning"} loading={mutation.isPending} disabled={!valid} onClick={() => { if (!valid || !confirmationValid || !cart || guard.current || mutation.isPending) return; guard.current = true; mutation.mutate({ id: cart._id, action, reason: reason.trim() }); }}>تأیید نهایی</DataButton></div></div> : null}</section>
    </div> : null}
  </DynamicModal>;
}
